In [ ]:
#Bug of Words

In [ ]:
!pip install sapcy
!python -m spacy download en_core_web_md

ERROR: Could not find a version that satisfies the requirement sapcy (from versions: none)
ERROR: No matching distribution found for sapcy
2024-01-31 21:14:08.099295: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-31 21:14:08.099398: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-31 21:14:08.103905: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-31 21:14:08.126611: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: A

In [ ]:
class category:
  Books='Books'
  Clothing='Clothing'

train_x=['I love books','This is a great book','The fit is great','I love the shoes']
train_y=[category.Books,category.Books,category.Clothing,category.Clothing]



In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

Vectorizer=CountVectorizer(binary=True,ngram_range=(1,2))
vectors=Vectorizer.fit_transform(train_x)

print(Vectorizer.get_feature_names_out())
print(vectors.toarray())

['book' 'books' 'fit' 'fit is' 'great' 'great book' 'is' 'is great' 'love'
 'love books' 'love the' 'shoes' 'the' 'the fit' 'the shoes' 'this'
 'this is']
[[0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 1]
 [0 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 0 0]]


In [ ]:
from sklearn import svm
clf_svm=svm.SVC(kernel='linear')
clf_svm.fit(vectors,train_y)


SVC(kernel='linear')

In [ ]:
text_x=Vectorizer.transform(['I like the books'])
clf_svm.predict(text_x)

array(['Books'], dtype='<U8')

In [ ]:
#Word Vector

In [ ]:
!pip install kaggle


In [ ]:
#Regular Expression



##Stemming and Lemmatization
 techniques to noramlize text
 read->reading
 books->book




#Twitter sentiment analysis

In [ ]:
! pip install kaggle

In [ ]:
#configurung the path of kaggle.json
! mkdir -p ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 6000 ~/.kaggle/kaggle.json

# Importing Twitter Sentiment Dataset

In [ ]:
# Api to fetch the dataset from kaggle
! kaggle datasets download -d kazanova/sentiment140


sentiment140.zip: Skipping, found more recently modified local copy (use --force to force download)


In [ ]:
#extracting the compressed dataset
from zipfile import ZipFile
dataset='/content/sentiment140.zip'

with ZipFile(dataset, 'r') as zip:
  zip.extractall()
  print('The dataset is extracted')

The dataset is extracted


Importing the dependecies

In [ ]:
import pandas as pd
import numpy as np
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


In [ ]:
import nltk
nltk.download('stopwords')
# A stop word is a word that does  not  add any meaning on your contextual data

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

Data processing

In [ ]:
# loading the dataset form csv file to pandas
twitter_dataset = pd.read_csv('/content/training.1600000.processed.noemoticon.csv',encoding = 'ISO-8859-1')

In [ ]:
# Checking the number of rows and  columns
twitter_dataset.shape

(1599999, 6)

In [ ]:
# Printing The first five rows of the data
twitter_dataset.head()

0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY _TheSpecialOne_  \
0  0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   scotthamilton   
1  0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY        mattycus   
2  0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY         ElleCTF   
3  0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY          Karoli   
4  0  1467811372  Mon Apr 06 22:20:00 PDT 2009  NO_QUERY        joy_wolf   

  @switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D  
0  is upset that he can't update his Facebook by ...                                                                   
1  @Kenichan I dived many times for the ball. Man...                                                                   
2    my whole body feels itchy and like its on fire                                                                    
3  @nationwideclass no, it's not behaving at all....                                                                   
4                      @Kwesidei not the whole crew

In [ ]:
#Naming the columns
colNames= ['target','ids','date','flag','user','text']
twitter_dataset = pd.read_csv('/content/training.1600000.processed.noemoticon.csv',names = colNames,encoding = 'ISO-8859-1')


In [ ]:
twitter_dataset.head()

target         ids                          date      flag  \
0       0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY   
1       0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   
2       0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
3       0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
4       0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   

              user                                               text  
0  _TheSpecialOne_  @switchfoot http://twitpic.com/2y1zl - Awww, t...  
1    scotthamilton  is upset that he can't update his Facebook by ...  
2         mattycus  @Kenichan I dived many times for the ball. Man...  
3          ElleCTF    my whole body feels itchy and like its on fire   
4           Karoli  @nationwideclass no, it's not behaving at all....

In [ ]:
# counting the number of missing values of the dataset
twitter_dataset.isnull().sum()

target    0
ids       0
date      0
flag      0
user      0
text      0
dtype: int64

In [ ]:
twitter_dataset['target'].value_counts()

0    800000
4    800000
Name: target, dtype: int64

In [ ]:
twitter_dataset.replace({'target':{4:1}},inplace=True)

In [ ]:
twitter_dataset['target'].value_counts()

0    800000
1    800000
Name: target, dtype: int64

0 neg, 1 pos

## Stemming
* Its a process of reducing a word to its root word
* reducess process of processing large dataset

In [ ]:
portStem=PorterStemmer()

def stemming(content):
  stemmedContent= re.sub('[^a-zA-Z]',' ',content)
  stemmedContent=stemmedContent.lower()
  stemmedContent=stemmedContent.split()
  stemmedContent=[portStem.stem(word) for word in stemmedContent if not word in stopwords.words('english')]
  stemmedContent=' '.join(stemmedContent)
  return stemmedContent

In [ ]:
twitter_dataset['stemmedContent'] = twitter_dataset['text'].apply(stemming)

In [ ]:
print(twitter_dataset)

         target         ids                          date      flag  \
0             0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY   
1             0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   
2             0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
3             0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
4             0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
...         ...         ...                           ...       ...   
1599995       1  2193601966  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599996       1  2193601969  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599997       1  2193601991  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599998       1  2193602064  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599999       1  2193602129  Tue Jun 16 08:40:50 PDT 2009  NO_QUERY   

                    user                                               text  \
0        _TheSpecialOne_  @switchfoot http://twitpic.com/2y1zl - Aww

In [ ]:
#separating the data and the label
X = twitter_dataset['stemmedContent'].values
Y= twitter_dataset['target'].values

In [ ]:
print(X)


['switchfoot http twitpic com zl awww bummer shoulda got david carr third day'
 'upset updat facebook text might cri result school today also blah'
 'kenichan dive mani time ball manag save rest go bound' ...
 'readi mojo makeov ask detail'
 'happi th birthday boo alll time tupac amaru shakur'
 'happi charitytuesday thenspcc sparkschar speakinguph h']


In [ ]:
print(Y)

[0 0 0 ... 1 1 1]


In [ ]:

# splitting the data into train and test data

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size = 0.25,stratify = Y,random_state = 2)

In [ ]:
# Converting the textual data to numerical data

vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [ ]:
print(X_train)

  (0, 76623)	0.3079421596528722
  (0, 173944)	0.27361083420633164
  (0, 353480)	0.31024983563960834
  (0, 347166)	0.28801409672291506
  (0, 76067)	0.26933867919175003
  (0, 403997)	0.24502287044549792
  (0, 374356)	0.448146199728837
  (0, 237343)	0.23303345421625404
  (0, 365189)	0.5132080660144132
  (1, 419352)	0.25706702258069447
  (1, 232174)	0.17010366621372047
  (1, 102200)	0.23313119944256036
  (1, 27594)	0.2489748661913732
  (1, 161685)	0.19896977936288707
  (1, 418472)	0.33235992111366175
  (1, 372368)	0.256832440572957
  (1, 417988)	0.3404716584815899
  (1, 74743)	0.26384919818910885
  (1, 327520)	0.5889858120350424
  (1, 75463)	0.20046450884815895
  (2, 19892)	0.25851264547753383
  (2, 390630)	0.32485953666504225
  (2, 122157)	0.2567074056592465
  (2, 144467)	0.20332052692124486
  (2, 170687)	0.17505789138153294
  :	:
  (1199995, 441344)	0.38423553348045847
  (1199995, 380922)	0.33412704097576246
  (1199995, 28119)	0.34317222539429654
  (1199995, 120816)	0.3438709016302232
  

In [ ]:
print(X_test)

  (0, 396888)	0.3522679708361543
  (0, 288731)	0.279794468955125
  (0, 165295)	0.27283113951697135
  (0, 162747)	0.34342514882547964
  (0, 155084)	0.26850580709852695
  (0, 153988)	0.24966370327216753
  (0, 142254)	0.2816038871445881
  (0, 83586)	0.46809413234577185
  (0, 29794)	0.2065818431550562
  (0, 2660)	0.3601783047868634
  (1, 427020)	0.34364342763470335
  (1, 421479)	0.3188692473686777
  (1, 267393)	0.20801913348714463
  (1, 157078)	0.6215471764912583
  (1, 154194)	0.3619263202636623
  (1, 143622)	0.1524821950529528
  (1, 127362)	0.241680550521661
  (1, 119508)	0.3338431294300748
  (1, 89868)	0.1629004007027813
  (2, 403364)	0.2117688080216412
  (2, 366053)	0.23383296032169892
  (2, 313254)	0.26827307453006766
  (2, 286263)	0.29500402660299
  (2, 230724)	0.2079697128335293
  (2, 225144)	0.1760051569672463
  :	:
  (399996, 394299)	0.1918649747558794
  (399996, 267912)	0.3309813811971613
  (399996, 241630)	0.3775126043628339
  (399996, 144467)	0.24081453257477542
  (399996, 61399

## Training the machine larning model using logistic regressionmodel

In [ ]:
model = LogisticRegression(max_iter=1000)

In [ ]:
model.fit(X_train,Y_train)

LogisticRegression(max_iter=1000)

## Model Evaluation
*  Accuracy score

In [ ]:
X_train_prediction= model.predict(X_train)
training_data_accuracy = accuracy_score(Y_train,X_train_prediction)
print('Accuracy:',training_data_accuracy)

Accuracy: 0.8103291666666667


In [ ]:
# x test prediction,,,,overfitting is where training accuracy is higher than the test accuracy
X_test_prediction= model.predict(X_test)
training_data_accuracy = accuracy_score(Y_test,X_test_prediction)
print('Accuracy:',training_data_accuracy)

Accuracy: 0.77806


## Saving the trained model

In [ ]:
import pickle

In [ ]:
filename = 'trainModel.sav'
pickle.dump(model,open(filename,'wb'))

## Using the saved model for feature prediction

In [ ]:
loadeModel = pickle.load(open('/content/trainModel.sav','rb'))